import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React from "react";
import { IoIosPerson } from 'react-icons/io';
import { IoIosUnlock } from 'react-icons/io';
import Router from 'next/router'
import { store } from '../src/store'
import * as Action from '../src/actions'
class home extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      userName: "", passWord: "", loginChecked: 0
    }
    //this.fetchSymbol();
    //console.log(JSON.stringify(sessionStrategyList))
  }
  getHistoricalData = async () => {
    // console.log("Historical data");
  }
  handleChange(evt) {
    const value = evt.target.value;
    if (value) {

      this.setState({
        [evt.target.name]: value
      });
      //}
    } else {
      this.setState({
        [evt.target.name]: ''
      });
    }
    console.log(evt.target.name + " " + evt.target.value)
  }
  componentDidMount() {
    this.getHistoricalData();
  }
  LoginClicked = (userName, passWord) => {
    if (this.state.userName.length < 1 && this.state.passWord < 1) {
      alert('Please enter username and password');
    } else {
      store.dispatch(Action.default.login({ login: true, email: userName }));
      Router.router.push("/dashboard")
    }
  }

  render() {

    return (
      <div className={styles.container}>

        <Head>
          <title>Admin Strategy</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main>
          <div class="login-page bg-light">
            <div class="container">
              <div class="row">
                <div class="col-lg-10 offset-lg-1">
                  <h3 class="mb-3">Login</h3>
                  <div class="bg-white shadow rounded">
                    <div class="row">
                      <div class="col-md-7 pe-0">
                        <div class="form-left h-100 py-5 px-5">
                          <div class="row g-4">
                            <div class="col-12">
                              <label>Username<span class="text-danger">*</span></label>
                              <div class="input-group">
                                <div class="input-group-text"><IoIosPerson /></div>
                                <input type="text" name="userName" value={this.state.userName ? this.state.userName : ""} onChange={(evt) => { this.handleChange(evt) }} class="form-control" placeholder="Enter Username" />
                              </div>
                            </div>

                            <div class="col-12">
                              <label>Password<span class="text-danger">*</span></label>
                              <div class="input-group">
                                <div class="input-group-text"><IoIosUnlock /></div>
                                <input type="password" name="passWord" value={this.state.passWord ? this.state.passWord : ""} onChange={(evt) => { this.handleChange(evt) }} class="form-control" placeholder="Enter Password" />
                              </div>
                            </div>

                            <div class="col-sm-6">
                              <div class="form-check">
                                <input class="form-check-input" type="checkbox" id="inlineFormCheck" />
                                <label class="form-check-label" for="inlineFormCheck">Remember me</label>
                              </div>
                            </div>

                            <div class="col-sm-6">
                              <a href="#" class="float-end text-primary">Forgot Password?</a>
                            </div>

                            <div class="col-12">
                              <button onTouchStartCapture={() => { this.LoginClicked(this.state.userName, this.state.passWord) }} onClick={() => { this.LoginClicked(this.state.userName, this.state.passWord) }} class="btn btn-primary px-4 float-end mt-4">Login</button>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div class="col-md-5 ps-0 d-none d-md-block">
                        <div class="form-right h-100 bg-primary text-white text-center pt-5">
                          <h2 class="fs-1">Welcome Back!!!</h2>
                        </div>
                      </div>
                    </div>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </main>

        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{' '}
            <span className={styles.logo}>
              <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
            </span>
          </a>
        </footer>
      </div>
    )
  }
}
export default home;
